---
version: 1
formatters:
  standard:
    format: '%(asctime)s - %(levelname)s - %(filename)s %(lineno)s %(funcName)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: standard
root:
  level: DEBUG
  handlers: [ console ]
